package at.database;
// Generated 18.12.2017 13:26:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer coursePk;
     private String title;
     private String description;
     private Integer duration;
     private String semester;
     private Set personCourseMemberships = new HashSet(0);

    public Course() {
    }

	
    public Course(String title, String description, Integer duration, String semester) {
        this.title = title;
        this.description = description;
        this.duration = duration;
        this.semester = semester;
    }
    public Course(String title, String description, Integer duration, String semester, Set personCourseMemberships) {
       this.title = title;
       this.description = description;
       this.duration = duration;
       this.semester = semester;
       this.personCourseMemberships = personCourseMemberships;
    }
   
    public Integer getCoursePk() {
        return this.coursePk;
    }
    
    public void setCoursePk(Integer coursePk) {
        this.coursePk = coursePk;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Set getPersonCourseMemberships() {
        return this.personCourseMemberships;
    }
    
    public void setPersonCourseMemberships(Set personCourseMemberships) {
        this.personCourseMemberships = personCourseMemberships;
    }




}


