package at.database;
// Generated 21.12.2017 18:52:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer coursePk;
     private String title;
     private String description;
     private int duration;
     private String semester;
     private Set personCourseMemberships = new HashSet(0);
     private Integer grade;
     private String lecturer;

    public String getLecturer() {
        return lecturer;
    }

    public void setLecturer(String lecturer) {
        this.lecturer = lecturer;
    }

    public Integer getGrade() {
        return grade;
    }

    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    public Course() {
    }

	
    public Course(String title, String description, int duration, String semester) {
        this.title = title;
        this.description = description;
        this.duration = duration;
        this.semester = semester;
    }
    public Course(String title, String description, int duration, String semester, Set personCourseMemberships) {
       this.title = title;
       this.description = description;
       this.duration = duration;
       this.semester = semester;
       this.personCourseMemberships = personCourseMemberships;
    }
   
    public Integer getCoursePk() {
        return this.coursePk;
    }
    
    public void setCoursePk(Integer coursePk) {
        this.coursePk = coursePk;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Set getPersonCourseMemberships() {
        return this.personCourseMemberships;
    }
    
    public void setPersonCourseMemberships(Set personCourseMemberships) {
        this.personCourseMemberships = personCourseMemberships;
    }




}


